### ISSUE TITLE
Persist state on re-deploy not working inside subflow

### ISSUE THREAD

**Issue by johnstav** [hufftheweevil/node-red-contrib-persistent-fsm#10]
Steps to reproduce:
1. Create a subflow
2. Add a state-machine node and configure with states / triggers
3. Save subflow and add to subflow to a flow
4. Change state of state-machine through subflow
5. Redeploy
6. State is reverted to intial state

**Comment by hufftheweevil** [comment]
Fixed in [v1.2.1](https://github.com/hufftheweevil/node-red-contrib-persistent-fsm/releases/tag/v1.2.1) Thank you!
