### ISSUE TITLE
State Machine - How to Compare Numbers?

### ISSUE THREAD

**Issue by wilwizard1979** [hufftheweevil/node-red-contrib-persistent-fsm#11]
Hello, I´m trying to learn and do some tests with the State Machine Node, but I´m having problems to use number comparisons. The = works fine, but the > #number seems to require a certain syntax that I´m not sure.

Below the very simple flow I´m testing:
![image](https://user-images.githubusercontent.com/108979356/204161189-ee3d2242-1ac1-4708-9bbf-a2853b1451e0.png)

And the configuration inside:

![image](https://user-images.githubusercontent.com/108979356/204161203-20e718b4-d809-4e9e-897b-65572c2eb982.png)

The >400 doesn´t work and it seems the Node waits for a string ">400" but not an actual number that is over 400.

The trigger State Node is configured to Number.
What am I doing wrong?

**Comment by hufftheweevil** [comment]
Traditionally, FSMs don't usually accept triggers/cases that are conditionals like that. I don't have any plans to modify this node to accept stuff like that. However, an easy solution is to add a node(s) before the state machine that checks the value and changes it to `">400"` if it is indeed over 400. This could be done many ways, but probably the easiest would be with a `function` node with the following:
```
if (msg.payload > 400) msg.payload = ">400" // or check whatever property you're using for the trigger
return msg
```

**Comment by hufftheweevil** [comment]
Closing for now, but please feel free to ask more questions if you have any
