### ISSUE TITLE
Node does not save state when redeployed

### ISSUE THREAD

**Issue by vvzvlad** [hufftheweevil/node-red-contrib-persistent-fsm#12]
I have created a simple automaton consisting of three states and three triggers. Everything works fine, as long as I'm just playing with it, the states switch, no extra messages are displayed. Everything goes as it should. 
But if I'm not in default state and make a deployment, the node switches to default state, despite "Persist state on re-deploy" checkbox. 
What I expect from the "Persist state on re-deploy" checkbox is that the node's state will only be reset when the entire NodeRED is rebooted. I have recorded a short video with a demonstration. The version of nodered is 3.0.2, node-red-contrib-persistent-fsm is 1.2.1. 

https://mega.nz/file/zwBkHKxB#ct0z15SjTgHjQnQSVAMwyNdsqxM8gIXSnufx4oHJOyA

**Comment by hufftheweevil** [comment]
Please export that flow and paste it here so I can easily recreate the scenario.
Thanks

**Comment by vvzvlad** [comment]
Unfortunately, I've already removed the test scheme and node from my NodeRED, as I can't use it properly, and wrote my own implementation of the state machine

**Comment by hufftheweevil** [comment]
Sorry to hear that, but glad you got something working. I set up, what I think, is a similar demo as to what you posted. And I was unable to reproduce the bug. If anyone else has this problem too, please feel free to post here and I will re-open.
