### ISSUE TITLE
State machine breaks on numeric Trigger input

### ISSUE THREAD

**Issue by jlsjonas** [hufftheweevil/node-red-contrib-persistent-fsm#5]
When serving a numeric trigger input, the code crashes with `"TypeError: label.split is not a function"` as it's trying to parse the input as a string label & split it (which is not a valid operation on a number)

use-case: counting number of taps within a short time (double-tap emulation) to control transitions (while protecting from invalid states & keeping track of the current state)

**Comment by hufftheweevil** [comment]
Fixed with https://github.com/hufftheweevil/node-red-contrib-persistent-fsm/commit/b6e944d2a2de2e92f265c15c7d22a1e61127eff4
